# Generated by Django 4.2.5 on 2023-10-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0002_usermentor_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermentor',
            name='expertise',
        ),
    ]
